apiVersion: apps/v1
kind: Deployment
metadata:
  name: 142-nginx-deployment
  labels:
    app: 142-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: 142-nginx
  template:
    metadata:
      labels:
        app: 142-nginx
    spec:
      containers:
      - name: nginx
        image: 172.1.14.168:5001/nginx
        ports:
        - containerPort: 80

Command to deploy:
	kubectl apply -f dep.yaml

Command to check pods
	kubectl get pods | grep ‘142’   \\ type your usn

Command to expose
	kubectl expose deployment 142-nginx-deployment --type=NodePort --name=142-nginx-service

To get exposed port
	kubectl get svc | grep ‘142’  \\ type your usn
             http://172.1.14.168:<nodeport>
                
 .
  kubectl port-forward deployment/142-nginx-deployment  newport:<nodeport>

