apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
  - name: ubuntu
    image: 172.1.14.168:5001/ubuntu
    command: ["/bin/bash"]
    args: ["-c", "echo MSRIT"]

kubectl apply -f dep4.yaml
kubectl logs ubuntu
kubectl exec --stdin --tty ubuntu -- /bin/bash
kubectl delete pod ubuntu
